### ISSUE TITLE
file output 0 bytes

### ISSUE THREAD

**Issue by pin8all** [minimaxir/video-to-gif-osx#1]
Installed per instructions, no errors. Using the app, or the workflow through services, the gif file is generated but 0 bytes.

**Comment by minimaxir** [comment]
Others in my [blog post comments](http://minimaxir.com/2015/08/gif-to-video-osx/) are saying the same thing.

If the GIF is empty, that means the script failed partially. Make sure the 3 tools are installed correctly (run the `brew` command again), and use the Shell Script from the Terminal to debug. (it will give an error message where the script fails)

Also, make sure you're using with Quicktime files. It _should_ work with all video files (uses ffmpeg as underlying codec), but .avis can be jerks.

**Comment by minimaxir** [comment]
I added a test case in https://github.com/minimaxir/video-to-gif-osx/commit/932fd3c86d126a0631cd8033c19555a9dc86e459

Let me know what the output of that is.

**Comment by minimaxir** [comment]
That commit didn't work fully.

I think I fixed it. In Automator and Services, you should use the absolute path to the external program functions. (e.g. `/usr/local/bin/mplayer`). With this approach the bash profile is no longer needed so that issue is out of play.

I updated the repo. Let me know if the Automator app works for you now.

**Comment by pin8all** [comment]
Works great now - thanks so much for following up. Tested with a variety of videos and all concerted ok.
